test globbing with grep
Signed-off-by: Mike Szczys <mike@golioth.io>

diff --git a/.github/actions/safe-upload-artifacts/action.yml b/.github/actions/safe-upload-artifacts/action.yml
--- a/.github/actions/safe-upload-artifacts/action.yml
+++ b/.github/actions/safe-upload-artifacts/action.yml
@@ -29,32 +29,32 @@ runs:
           fi
         fi
 
-    - name: Generate list of files to mask
-      shell: bash
-      run: |
-        rm -rf files_to_search.txt
-        rm -rf found_files.txt
-        touch found_files.txt
+    #- name: Generate list of files to mask
+      #shell: bash
+      #run: |
+        #rm -rf files_to_search.txt
+        #rm -rf found_files.txt
+        #touch found_files.txt
 
-        # Enable globbing
-        shopt -s globstar
+        ## Enable globbing
+        #shopt -s globstar
 
-        # Iterate list of input paths and use find to create a file list from the patterns
-        while IFS= read -r line || [[ -n $line ]]; do
-          echo $line
-          [ $(find "${line}" -type f 2>/dev/null >> found_files.txt) >= 0 ]
-        done < <(printf '%s' "${{ inputs.path }}")
+        ## Iterate list of input paths and use find to create a file list from the patterns
+        #while IFS= read -r line || [[ -n $line ]]; do
+          #echo $line
+          #[ $(find "${line}" -type f 2>/dev/null >> found_files.txt) >= 0 ]
+        #done < <(printf '%s' "${{ inputs.path }}")
 
-        uniq found_files.txt > files_to_search.txt
+        #uniq found_files.txt > files_to_search.txt
 
-        if [ ! -s files_to_search.txt ]; then
-          echo "Failed to find any files to process. Check path input."
-          rm found_files.txt
-          rm files_to_search.txt
-          exit 1
-        fi
+        #if [ ! -s files_to_search.txt ]; then
+          #echo "Failed to find any files to process. Check path input."
+          #rm found_files.txt
+          #rm files_to_search.txt
+          #exit 1
+        #fi
 
-        rm found_files.txt
+        #rm found_files.txt
 
     - name: Find and mask
       id: find-and-mask
@@ -62,6 +62,9 @@ runs:
       env:
         SECRETS_CONTEXT: '${{ inputs.secrets-json }}'
       run: |
+        # Enable globbing
+        shopt -s globstar
+
         for key in $(jq -r "keys[]" <<< "$SECRETS_CONTEXT");
         do
           secret_val=$(jq -r ".$key" <<< "$SECRETS_CONTEXT")
@@ -70,13 +73,10 @@ runs:
             # This approach to escaping the regex found: https://stackoverflow.com/a/29613573/922013
             ESCAPED_SECRET=$(sed 's/[^^]/[&]/g; s/\^/\\^/g' <<< "$secret_val")
 
-            cat files_to_search.txt | while read search_file
-            do
-              if [ -f $search_file ]; then
-                # Always return true, otherwise a grep that doesn't find files will cause step to fail
-                [ $(grep -Rl $ESCAPED_SECRET $search_dir > files_with_secret.txt) >= 0 ]
-              fi
-            done
+            # Iterate list of input paths and use find to create a file list from the patterns
+            while IFS= read -r search_path || [[ -n $search_path ]]; do
+              [ $(grep -Rl $ESCAPED_SECRET $search_path > files_with_secret.txt) >= 0 ]
+            done < <(printf '%s' "${{ inputs.path }}")
 
             uniq files_with_secret.txt > file_list.txt
 
