CI: zephyr: package individual suite reports and display as one
collect the xml twister summary from each parallel test and process them as
a single report containing all sample tests for the same HIL device.

Signed-off-by: Mike Szczys <mike@golioth.io>

diff --git a/.github/workflows/hil-sample-zephyr.yml b/.github/workflows/hil-sample-zephyr.yml
--- a/.github/workflows/hil-sample-zephyr.yml
+++ b/.github/workflows/hil-sample-zephyr.yml
@@ -259,20 +259,12 @@ jobs:
             twister-out/*.xml
             twister-out/*.json
 
-      - name: Prepare CI report summary
-        if: success() || failure()
-        run: |
-          rm -rf summary
-          mkdir summary
-          cp twister-out/twister_suite_report.xml \
-             summary/samples-zephyr-${{ inputs.hil_board }}-${{ matrix.name }}.xml
-
       - name: Safe upload CI report summary
         uses: ./modules/lib/golioth-firmware-sdk/.github/actions/safe-upload-artifacts
         if: success() || failure()
         with:
-          name: ci-summary-samples-zephyr-${{ inputs.hil_board }}-${{ matrix.name }}
-          path: summary/*
+          name: ci-individual-samples-zephyr-${{ inputs.hil_board }}-${{ matrix.name }}
+          path: twister-out/twister_suite_report.xml
 
       - name: Safe upload Allure reports
         if: success() || failure()
@@ -347,3 +339,47 @@ jobs:
         uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe
         with:
           jobs: ${{ toJSON(needs) }}
+
+  hil_sample_zephyr_nsim_summary:
+    name: zephyr-${{ inputs.hil_board }}-twister-summary
+    runs-on: ubuntu-24.04
+    needs:
+      - matrix
+      - build
+      - test
+    if: success() || failure()
+
+    steps:
+      - name: Collect JUnit reports
+        uses: actions/download-artifact@v4
+        with:
+          pattern: ci-individual-samples-zephyr-*
+
+      - name: Prepare CI report summary
+        if: success() || failure()
+        run: |
+          sudo apt install -y xml-twig-tools
+
+          rm -rf summary
+          mkdir summary
+
+          find ci-individual-samples-zephyr-${{ inputs.hil_board }}-* \
+            -name "twister_suite_report.xml"
+
+          if [ $? -eq 0 ]; then
+            # If twister_suite_report.xml is not present (build steps fail, etc), xml_grep will fail
+            # Prevent summary job from failing for all devices by skipping when file not found
+
+            xml_grep --pretty_print indented \
+              --wrap testsuites --descr '' \
+              --cond "testsuite" \
+              ci-individual-samples-zephyr-${{ inputs.hil_board }}*/*.xml \
+              > samples-zephyr-${{ inputs.hil_board }}.xml
+          fi
+
+      - name: Upload CI report summary
+        uses: actions/upload-artifact@v4
+        if: success() || failure()
+        with:
+          name: ci-summary-samples-zephyr-${{ inputs.hil_board }}
+          path: samples-zephyr-*.xml
