ci: config update to test against dev
Configuration changes required in order to test against
dev instead of prod.

Made a couple of other changes outside of the repo:

1. Update credentials.yml on all self-hosted runners to
   set api_url to https://api.golioth.dev.
2. Set the repo GOLIOTH_API_KEY secret to the API key of
   the test project on golioth.dev

Signed-off-by: Nick Miller <nick@golioth.io>

diff --git a/.github/workflows/test_esp32s3.yml b/.github/workflows/test_esp32s3.yml
--- a/.github/workflows/test_esp32s3.yml
+++ b/.github/workflows/test_esp32s3.yml
@@ -61,12 +61,13 @@ jobs:
         GOLIOTH_API_KEY: ${{ secrets.GOLIOTH_API_KEY }}
       run: |
         cd examples/esp_idf/test
-        goliothctl login --apiKey $GOLIOTH_API_KEY
-        goliothctl config set projectId ci
-        goliothctl dfu release delete 1.2.99 || echo "release not found"
-        goliothctl dfu artifact delete 1.2.99 || echo "artifact not found"
-        goliothctl dfu artifact create build/test.bin --version 1.2.99
-        goliothctl dfu release create --release-tags 1.2.99 --components main@1.2.99 --rollout true
+        export GOLIOTH_API_URL=https://api.golioth.dev
+        export GOLIOTH_PROJECT_ID=ci
+        goliothctl login --apiUrl $GOLIOTH_API_URL --projectId $GOLIOTH_PROJECT_ID --apiKey $GOLIOTH_API_KEY
+        goliothctl dfu --apiUrl $GOLIOTH_API_URL --projectId $GOLIOTH_PROJECT_ID release delete 1.2.99 || echo "release not found"
+        goliothctl dfu --apiUrl $GOLIOTH_API_URL --projectId $GOLIOTH_PROJECT_ID artifact delete 1.2.99 || echo "artifact not found"
+        goliothctl dfu --apiUrl $GOLIOTH_API_URL --projectId $GOLIOTH_PROJECT_ID artifact create build/test.bin --version 1.2.99
+        goliothctl dfu --apiUrl $GOLIOTH_API_URL --projectId $GOLIOTH_PROJECT_ID release create --release-tags 1.2.99 --components main@1.2.99 --rollout true
 
   # Assumptions made about the self-hosted runner:
   #
@@ -93,6 +94,7 @@ jobs:
   #   golioth/psk: supersecret
   #
   # golioth_api:
+  #   api_url: https://api.golioth.dev
   #   project_id: project
   #   device_id: deviceid
   #   api_key: apikey
